export const galleryData = [
  { slug: 'the-lush-canopy', img: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=800&q=80', title: 'The Lush Canopy', category: 'Planted Aquascape', desc: 'A dense, vibrant underwater forest designed to mimic natural Amazonian streams.' },
  { slug: 'stone-monoliths', img: 'https://images.unsplash.com/photo-1543822765-6b45a4a5840d?w=800&q=80', title: 'Stone Monoliths', category: 'Hardscape Design', desc: 'Dramatic vertical stone formations creating a minimalist yet powerful architectural presence.' },
  { slug: 'river-bed-biotope', img: 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=800&q=80', title: 'River Bed Biotope', category: 'Natural Biotope', desc: 'A meticulously crafted environment representing a natural riverbed with smooth stones and drifting wood.' },
  { slug: 'emerald-cascade', img: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80', title: 'Emerald Cascade', category: 'Dutch Style', desc: 'Lush terraced planting in the classic Dutch style, focusing on color contrast and texture.' },
  { slug: 'rainforest-edge', img: 'https://images.unsplash.com/photo-1620601332737-1425e408ec21?w=800&q=80', title: 'Rainforest Edge', category: 'Paludarium', desc: 'Where land meets water, this paludarium blends terrestrial ferns with aquatic mosses.' },
  { slug: 'driftwood-sanctuary', img: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80', title: 'Driftwood Sanctuary', category: 'Hardscape', desc: 'Intricate intertwined driftwood providing a safe haven and striking visual complexity.' },
  { slug: 'twilight-reef', img: 'https://images.unsplash.com/photo-1611462985358-60d3498e0364?w=800&q=80', title: 'Twilight Reef', category: 'Marine Setup', desc: 'A vibrant marine ecosystem glowing under specialized actinic lighting.' },
  { slug: 'botanical-balance', img: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80', title: 'Botanical Balance', category: 'Terrarium', desc: 'A self-sustaining enclosed terrestrial ecosystem thriving in perfect humidity.' }
]
